name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
  repository_dispatch:

jobs:
  test-and-publish:
    name: Test and publish
    uses: significa/actions/.github/workflows/npm-library.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      lint_command: npm run validate
      publish_to_npm_registry: true
      publish_to_github_registry: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-storybook:
    name: Deploy to Storyblok
    permissions:
      contents: read
      packages: read
      deployments: write
    uses: significa/actions/.github/workflows/vercel-app.yaml@vercel-deployment-alias
    with:
      lint_command: null
      test_command: null
      staging_domain: ${{ vars.STAGING_DOMAIN }}
      production_domain: ${{ vars.PRODUCTION_DOMAIN }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
